services:
  web:
    build: .
    container_name: fitness-app-container
    ports:
      - "5000:5000" # Changed from 8000 to 5000 to match Flask's default port
    volumes:
      - .:/app
    env_file:
      - .env


# services:
#   web:
#     build: .
#     container_name: fitness-app-container
#     ports:
#       - "8000:8000"
#     volumes:
#       - .:/app
#     env_file:
#       - .env
#     # This correctly bypasses the entrypoint.sh script
#     entrypoint: sleep infinity