"""add token blocklist model

Revision ID: 33111e560388
Revises: f7fca6375ac7
Create Date: 2025-08-03 19:28:12.613159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33111e560388'
down_revision = 'f7fca6375ac7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # This migration file has been manually edited to only create the new table.
    
    op.create_table('token_blocklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='neondb'
    )
    with op.batch_alter_table('token_blocklist', schema='neondb') as batch_op:
        batch_op.create_index(batch_op.f('ix_neondb_token_blocklist_jti'), ['jti'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # This downgrade function has been manually edited to only drop the new table.
    
    with op.batch_alter_table('token_blocklist', schema='neondb') as batch_op:
        batch_op.drop_index(batch_op.f('ix_neondb_token_blocklist_jti'))

    op.drop_table('token_blocklist', schema='neondb')
    
    # ### end Alembic commands ###
