"""add RefreshToken model

Revision ID: a6bda456d231
Revises: 33111e560388
Create Date: 2025-08-04 06:48:13.940628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6bda456d231'
down_revision = '33111e560388'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=256), nullable=False),
    sa.Column('expiry_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['neondb.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='neondb'
    )
    with op.batch_alter_table('refresh_token', schema='neondb') as batch_op:
        batch_op.create_index(batch_op.f('ix_neondb_refresh_token_token'), ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refresh_token', schema='neondb') as batch_op:
        batch_op.drop_index(batch_op.f('ix_neondb_refresh_token_token'))

    op.drop_table('refresh_token', schema='neondb')
    # ### end Alembic commands ###