"""add dietPlan model

Revision ID: bfa71af8822c
Revises: 0a8b33500b65
Create Date: 2025-07-29 14:49:31.335799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfa71af8822c'
down_revision = '0a8b33500b65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # This upgrade function ONLY creates the new 'diet_plan' table.
    op.create_table('diet_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('generated_plan', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['neondb.clients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['neondb.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='neondb'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # This downgrade function ONLY drops the new 'diet_plan' table.
    op.drop_table('diet_plan', schema='neondb')
    # ### end Alembic commands ###