"""add timezone support to refresh_token expiry_date

Revision ID: f9b80355be02
Revises: a6bda456d231
Create Date: 2025-08-10 16:07:39.099767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9b80355be02'
down_revision = 'a6bda456d231'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refresh_token', schema='neondb') as batch_op:
        batch_op.alter_column('expiry_date',
               existing_type=sa.DateTime(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refresh_token', schema='neondb') as batch_op:
        batch_op.alter_column('expiry_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DateTime(),
               nullable=False)
    # ### end Alembic commands ###