# This file goes in: .github/workflows/ci.yml

# Name of the workflow as it will appear in the GitHub Actions tab
name: Fitness Tracker CI

# --- Triggers ---
# This section defines when the workflow will run.
on:
  # Run this workflow on every push to any branch
  push:
    branches: [ "**" ]
  # Also run on every pull request to the main branch
  pull_request:
    branches: [ "main" ]

# --- Jobs ---
# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  # The "build-and-test" job
  build-and-test:
    # The type of virtual machine to run the job on. "ubuntu-latest" is a good default.
    runs-on: ubuntu-latest

    # A sequence of tasks that will be executed as part of the job
    steps:
      # Step 1: Check out your repository's code
      # This action checks-out your repository under $GITHUB_WORKSPACE, so your job can access it.
      - name: Check out repository code
        uses: actions/checkout@v4

      # Step 2: Set up the Python environment
      # This action sets up a Python environment for use in your workflow.
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          # Use the same Python version as your project
          python-version: '3.10'

      # Step 3: Install project dependencies
      # This step runs command-line programs to install your Python packages.
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest  # Good practice to explicitly install testing tools

      # Step 4: Run the tests using Pytest
      # This step executes your test suite. If any test fails, the workflow will fail.
      - name: Run tests with Pytest
        run: |
          pytest